apiVersion: v1
kind: Pod
metadata:
  name: kuard
spec:
  containers:
    - image: ksaito1125/kuard
      name: kuard
      resources:
        requests:
          cpu: "500m"
          memory: "128Mi"
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
  
